language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needed here"

before_script:
  - echo "no test here"


script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed higharc91/udagram-frontend:v1
  - docker tag udagram-api-user higharc91/udagram-api-user:v1
  - docker tag udagram-api-feed higharc91/udagram-api-feed:v1
  - docker tag reverseproxy higharc91/reverseproxy
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push higharc91/udagram-frontend:v1
  - docker push higharc91/udagram-api-user:v1
  - docker push higharc91/udagram-api-feed:v1
  - docker push higharc91/reverseproxy
